#!/usr/bin/dh-exec

debian/android/activity_actions.txt  usr/lib/android-sdk/platforms/android-${ANDROID_API_LEVEL}/data
debian/android/broadcast_actions.txt usr/lib/android-sdk/platforms/android-${ANDROID_API_LEVEL}/data
debian/android/build.prop            usr/lib/android-sdk/platforms/android-${ANDROID_API_LEVEL}
debian/android/categories.txt        usr/lib/android-sdk/platforms/android-${ANDROID_API_LEVEL}/data
debian/android/features.txt          usr/lib/android-sdk/platforms/android-${ANDROID_API_LEVEL}/data
debian/android/package.xml           usr/lib/android-sdk/platforms/android-${ANDROID_API_LEVEL}
debian/android/sdk.properties        usr/lib/android-sdk/platforms/android-${ANDROID_API_LEVEL}
debian/android/service_actions.txt   usr/lib/android-sdk/platforms/android-${ANDROID_API_LEVEL}/data
debian/android/source.properties     usr/lib/android-sdk/platforms/android-${ANDROID_API_LEVEL}
debian/android/widgets.txt           usr/lib/android-sdk/platforms/android-${ANDROID_API_LEVEL}/data
development/tools/emulator/skins/*   usr/share/android-sdk-platform-${ANDROID_API_LEVEL}/emulator-skins
frameworks/base/core/res/res         usr/share/android-sdk-platform-${ANDROID_API_LEVEL}